export enum TranslationKeys {
  signIn = 'signIn',
  signUp = 'signUp',
  not_found_page = 'not_found_page',
  welcome_page = 'welcome_page',
  main_title = 'main_title',
  main_subtitle = 'main_subtitle',
  welcome_link_editor_heading = 'welcome_link_editor_heading',
  welcome_link_authorization_heading = 'welcome_link_authorization_heading',
  about_project_title_1 = 'about_project_title_1',
  about_project_subtitle_1 = 'about_project_subtitle_1',
  about_project_title_2 = 'about_project_title_2',
  about_project_subtitle_2 = 'about_project_subtitle_2',
  about_project_title_3 = 'about_project_title_3',
  about_project_subtitle_3 = 'about_project_subtitle_3',
  about_project_alt = 'about_project_alt',
  team = 'team',
  team_alt = 'team_alt',
  editor_search_bar_label = 'editor_search_bar_label',
  editor_button_change_endpoint = 'editor_button_change_endpoint',
  konstantin = 'konstantin',
  veranika = 'veranika',
  artem = 'artem',
}
